from typing import List, Dict, Any

MITRE_TECHNIQUES_SEED: List[Dict[str, Any]] = [
    {
        "id": "T1566.001",
        "technique_id": "T1566.001",
        "name": "Phishing: Spearphishing Attachment",
        "tactic": "Initial Access",
        "category": "mitre",
        "description": "Adversaries may send spearphishing emails with a malicious attachment in an attempt to gain access to victim systems. Common file types include Office documents with VBA macros (.docm, .xlsm), PDF files, or ISO containers.",
        "detection": "Monitor for anomalous child processes spawned from email clients or document readers (e.g. WINWORD.EXE spawning powershell.exe or cmd.exe).",
        "mitigation": "Block macro execution in Office documents from untrusted sources. Use email filtering for executable attachments.",
        "reliability_weight": 1.0,
    },
    {
        "id": "T1059.001",
        "technique_id": "T1059.001",
        "name": "Command and Scripting Interpreter: PowerShell",
        "tactic": "Execution",
        "category": "mitre",
        "description": "Adversaries may abuse PowerShell commands and scripts for execution. PowerShell can download payloads, execute in-memory shellcode, and bypass execution policies via -Enc (encoded commands) or -ExecutionPolicy Bypass.",
        "detection": "Enable Script Block Logging (Event ID 4104) and Module Logging (Event ID 4103). Flag command-lines with base64 encoded strings (-Enc, -EncodedCommand) or hidden window styles (-W Hidden).",
        "mitigation": "Enforce PowerShell Constrained Language Mode and AppLocker script rules.",
        "reliability_weight": 1.0,
    },
    {
        "id": "T1046",
        "technique_id": "T1046",
        "name": "Network Service Discovery",
        "tactic": "Discovery",
        "category": "mitre",
        "description": "Adversaries may attempt to get a listing of services running on remote hosts to identify vulnerable systems or pivot targets. This includes TCP/UDP port scans against internal subnets.",
        "detection": "Detect high-frequency SYN packets or rapid sequential connection attempts to ports 445, 139, 3389, 22 across multiple internal IPs from a single workstation.",
        "mitigation": "Segment networks with internal firewalls and disable unused services.",
        "reliability_weight": 1.0,
    },
    {
        "id": "T1021.002",
        "technique_id": "T1021.002",
        "name": "Remote Services: SMB/Windows Admin Shares",
        "tactic": "Lateral Movement",
        "category": "mitre",
        "description": "Adversaries may use SMB to interact with administrative shares (C$, ADMIN$) to copy payloads and execute code remotely using PsExec or WMI.",
        "detection": "Monitor for SMB session setups followed immediately by service installations (Event ID 7045).",
        "mitigation": "Disable SMBv1 and restrict admin share access via group policy.",
        "reliability_weight": 1.0,
    },
    {
        "id": "T1110.001",
        "technique_id": "T1110.001",
        "name": "Brute Force: Password Guessing",
        "tactic": "Credential Access",
        "category": "mitre",
        "description": "Adversaries may systematically guess passwords for valid user accounts on protocols like SSH (port 22), FTP (port 21), or RDP (port 3389).",
        "detection": "Correlate multiple failed authentications (Event ID 4625 / auth.log failure) from a single IP within a short time window followed by an auth success (Event ID 4624).",
        "mitigation": "Enforce multi-factor authentication (MFA) and account lockout thresholds.",
        "reliability_weight": 1.0,
    },
    {
        "id": "T1190",
        "technique_id": "T1190",
        "name": "Exploit Public-Facing Application",
        "tactic": "Initial Access",
        "category": "mitre",
        "description": "Adversaries may take advantage of a weakness in an Internet-facing computer or program using software, data, or commands in order to cause unintended behavior (e.g. SQL Injection, RCE).",
        "detection": "Inspect web application logs and WAF alerts for SQL syntax (' OR 1=1, UNION SELECT, sqlmap signatures) or cross-site scripting tags.",
        "mitigation": "Use parameterized SQL queries, input sanitization, and regular security patching.",
        "reliability_weight": 1.0,
    },
    {
        "id": "T1071.001",
        "technique_id": "T1071.001",
        "name": "Application Layer Protocol: Web Protocols",
        "tactic": "Command and Control",
        "category": "mitre",
        "description": "Adversaries may communicate using application layer protocols (HTTP/HTTPS) to avoid detection by blending with existing network traffic. Botnets like Ares utilize periodic HTTP GET/POST beacons.",
        "detection": "Identify regular, periodic outbound connection intervals (jitter analysis) to untrusted or newly registered domain names and external IP addresses.",
        "mitigation": "Use web proxies with SSL inspection and domain reputation filtering.",
        "reliability_weight": 1.0,
    },
    {
        "id": "T1499.003",
        "technique_id": "T1499.003",
        "name": "Endpoint Denial of Service: Application Exhaustion",
        "tactic": "Impact",
        "category": "mitre",
        "description": "Adversaries may exhaust application resources by keeping connections open (Slowloris) or overwhelming web servers with concurrent requests (GoldenEye).",
        "detection": "Monitor server connection pools, thread starvation, and abnormally high ratios of partial HTTP headers.",
        "mitigation": "Implement aggressive timeout thresholds for slow connections and deploy reverse proxy rate limiting.",
        "reliability_weight": 1.0,
    },
]

RESPONSE_PLAYBOOKS_SEED: List[Dict[str, Any]] = [
    {
        "id": "PB-CRED-01",
        "name": "Credential Compromise & Password Spray Playbook",
        "category": "playbook",
        "target_threat": "T1110 - Brute Force",
        "description": "Containment and recovery steps when anomalous password spraying or successful brute force is detected on SSH/FTP/RDP.",
        "containment_steps": [
            "Block offending source IP address at border firewall.",
            "Temporarily lock or disable compromised user account.",
            "Terminate all active SSH/RDP sessions associated with the user.",
            "Enforce immediate password reset and verify MFA registration."
        ],
        "reliability_weight": 0.9,
    },
    {
        "id": "PB-INFIL-01",
        "name": "Workstation Infiltration & Reverse Shell Playbook",
        "category": "playbook",
        "target_threat": "T1566 / T1059 - Spearphishing & Scripting",
        "description": "Response workflow for suspicious document macro execution spawning command-line interpreters with outbound C2 connections.",
        "containment_steps": [
            "Network isolate the affected host (WORKSTATION-04) immediately.",
            "Terminate malicious PowerShell / parent process tree.",
            "Block external C2 destination IP / domain at corporate DNS and firewall.",
            "Collect memory dump and prefetch artifacts for forensics."
        ],
        "reliability_weight": 0.9,
    },
    {
        "id": "PB-WEB-01",
        "name": "Web Application SQL Injection Playbook",
        "category": "playbook",
        "target_threat": "T1190 - Exploit Public-Facing Application",
        "description": "Remediation workflow for SQL Injection and unauthorized database interrogation.",
        "containment_steps": [
            "Add offending IP address to WAF blacklist with 24-hour block rule.",
            "Inspect database transaction logs for extracted table names.",
            "Isolate the web application backend if database modification occurred.",
            "Apply security patch or parameterized query fix in code."
        ],
        "reliability_weight": 0.9,
    },
    {
        "id": "PB-C2-01",
        "name": "Botnet Command and Control Playbook",
        "category": "playbook",
        "target_threat": "T1071 - Application Layer C2",
        "description": "Containment protocol for recurring outbound botnet beacons.",
        "containment_steps": [
            "Sinkhole C2 server IP address on internal DNS/gateway.",
            "Isolate infected host from internal subnet.",
            "Identify persistence mechanism (Registry run keys, Scheduled tasks).",
            "Wipe and re-image the infected workstation."
        ],
        "reliability_weight": 0.9,
    },
]

HISTORICAL_CASES_SEED: List[Dict[str, Any]] = [
    {
        "id": "HIST-2025-081",
        "title": "Macro-Initiated PowerShell Beacon to Foreign Host",
        "category": "historical",
        "outcome": "confirmed_incident",
        "outcome_accuracy": 1.0,
        "mitre_techniques": ["T1566.001", "T1059.001", "T1071.001"],
        "summary": "Phishing email containing invoice.docm was opened. Word spawned PowerShell with base64 encoded payload, communicating with C2 server. Host was isolated within 12 minutes.",
        "reliability_weight": 0.8,
    },
    {
        "id": "HIST-2025-044",
        "title": "Automated SSH Password Spray Against Bastion",
        "category": "historical",
        "outcome": "confirmed_incident",
        "outcome_accuracy": 0.95,
        "mitre_techniques": ["T1110.001"],
        "summary": "External IP attempted 500+ logins across 30 usernames on port 22 within 3 minutes. Firewall IP block rule mitigated attack.",
        "reliability_weight": 0.8,
    },
]
